default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['BOOKSTORE_DATABASE_USERNAME'] %>
  password: <%= ENV['BOOKSTORE_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  database: bookstore
